---
id: ansel
name: Ansel
full: Photo gallery application
description: Ansel is a full featured photo gallery application.
list: ansel
type: application
homepage: https://www.horde.org/apps/ansel
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: true
    role: lead
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 4.0.0
  api: 4.0.0
state:
  release: beta
  api: beta
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/content: ^2.0.3
      pear.horde.org/horde: ^5
      pear.horde.org/Horde_Auth: ^2
      pear.horde.org/Horde_Autoloader: ^2
      pear.horde.org/Horde_Core: ^2.30
      pear.horde.org/Horde_Date: ^2
      pear.horde.org/Horde_Db: ^2.2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Form: ^2
      pear.horde.org/Horde_Group: ^2
      pear.horde.org/Horde_Image: ^2
      pear.horde.org/Horde_Mime: ^2
      pear.horde.org/Horde_Nls: ^2
      pear.horde.org/Horde_Perms: ^2
      pear.horde.org/Horde_Prefs: ^2
      pear.horde.org/Horde_Serialize: ^2
      pear.horde.org/Horde_Share: ^2
      pear.horde.org/Horde_Support: ^2
      pear.horde.org/Horde_Text_Filter: ^2
      pear.horde.org/Horde_Url: ^2
      pear.horde.org/Horde_Util: ^2
      pear.horde.org/Horde_View: ^2
      pear.horde.org/Horde_Vfs: ^2
    ext:
      gettext: '*'
      hash: '*'
  optional:
    pear:
      pear.horde.org/Horde_Service_UrlShortener: ^2
      pear.horde.org/Horde_Service_Twitter: ^2
      pear.horde.org/Horde_Service_Facebook: ^2
    ext:
      gd: '*'
      imagick: '*'
      libpuzzle: '*'
      php-facedetect: '*'
