---
id: ansel
name: Ansel
full: Photo gallery application
description: Ansel is a full featured photo gallery application.
list: ansel
type: application
homepage: https://www.horde.org/apps/ansel
authors:
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 4.0.0alpha3
  api: 4.0.0alpha1
state:
  release: beta
  api: beta
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^7
    composer:
      horde/content: ^3
      horde/horde: ^6
      horde/auth: ^3
      horde/autoloader: ^3
      horde/core: ^3
      horde/date: ^3
      horde/db: ^3
      horde/exception: ^3
      horde/form: ^3
      horde/group: ^3
      horde/image: ^3
      horde/mime: ^3
      horde/nls: ^3
      horde/perms: ^3
      horde/prefs: ^3
      horde/serialize: ^3
      horde/share: ^3
      horde/support: ^3
      horde/text_filter: ^3
      horde/url: ^3
      horde/util: ^3
      horde/view: ^3
      horde/vfs: ^3
    ext:
      gettext: '*'
      hash: '*'
  optional:
    composer:
      horde/service_urlShortener: ^3
      horde/service_twitter: ^3
      horde/service_facebook: ^3
    ext:
      gd: '*'
      imagick: '*'
      libpuzzle: '*'
      php-facedetect: '*'
